---
- name: Deploy concourse worker
  hosts: app
  vars_files:
    - ["vars/main.yml"]
    - ["vars/credential.yml"]
  handlers:
    - name: restart concourse-worker
      service: name=concourse-worker state=restarted
  tasks:
    - name: Copy upstart config for concourse worker
      template: src=templates/init-concourse-worker.j2 dest=/etc/init/concourse-worker.conf
      notify:
        - restart concourse-worker
